server:
  port: 12800
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
